S = <ite>
P = <ite>   ::= if_then_else <cmp> <ite> <ite> | 0 | 1 | 2
    <cmp> ::= <rel_op> <exp> const | <rel_op> <exp> <exp> | and <cmp> <cmp> | or <cmp> <cmp> | not <cmp>
    <rel_op> ::=  = | != | < | <= | > | >=
    <exp> ::= <bin_op> <atributo> <atributo> | <bin_op> <atributo> const | <un_op> <atributo>
    <un_op>  ::= abs | sqrt | pow2 | pow3 | pow4 | pow5 | neg | round
    <bin_op> ::= + | - | * | / | mean | max | min | mod | pow
    <atributo> ::= attr1 | attr2 | attr3 | attr4
    <const_numerico> ::= const
